### ISSUE TITLE
Unbinding should be done in reverse order of binding

### ISSUE THREAD

**Issue by BrunoDutertre** [cvc5/LFSC#67]
The following code pattern is used In several places in `check.cpp`

```
     DeclList decls = check_decl_list(false);
     // do stuff
     // restore old bindings
     for (const auto& binding : decls.old_bindings) {
        symbols->insert(get<0>(binding).c_str(), {get<1>(binding), get<2>(binding)});
     }
```

That's incorrect. The *restore old binding* part should be done in reverse order. 
Otherwise things go wrong if the same symbol is used several times in the bindings.

Here's an example:
```
(declare x type)
(declare sort type)
(declare-type bad ((: x sort) (: x sort)))
(declare b x)
```

**Comment by BrunoDutertre** [comment]
Note that this could be used to write an incorrect proof that lfscc won't reject.

**Comment by ajreynol** [comment]
Fixed by https://github.com/cvc5/LFSC/pull/76.

**Comment by alex-ozdemir** [comment]
Thanks, Bruno!
