### ISSUE TITLE
Integer division implemented as GMP cdiv

### ISSUE THREAD

**Issue by BrunoDutertre** [cvc5/LFSC#69]
In `code.cpp`, the evaluation of `(mp_div x y)` on integers relies on GMP's cdiv function:
```
mpz_cdiv_q(r, ((IntExpr*)r1)->n, ((IntExpr*)r2)->n);
```

This is a weird choice. It rounds toward +infinity. So for example `(mp_div 1 2)` is `1`.
It would make more sense to round toward 0 or toward -infinity.

It would also be nice to check for zero divisors.

Here's a test for this:
```
(run (mp_ifzero (mp_div 1 2) 0 1))
```
Result:
```
[Running-sc (ifzero (mp_div 1 2) 0 1)] = 
1
Proof checked successfully!
```

**Comment by ajreynol** [comment]
This sounds reasonable to me.
